In [1]:
import numpy as np
import pandas as pd

In [2]:
ella = pd.read_csv('ella_csp.csv')
emily = pd.read_csv('emily_csp.csv')
anish = pd.read_csv('anish_csp.csv')

In [25]:
ella2 = ella.set_index(['obj_id', 'feat_name'])
emily2 = emily.set_index(['obj_id', 'feat_name'])
anish2 = anish.set_index(['obj_id', 'feat_name'])
anish3 = anish2.rename(columns = {'pew' : 'pew_anish', 'pew_samperr' : 'pew_samperr_anish'})
inter = ella2.join(emily2, lsuffix = "_ella", rsuffix = '_emily')
combined = inter.join(anish3)

In [27]:
final = combined[['pew_ella', 'pew_samperr_ella', 'pew_emily', 'pew_samperr_emily', 'pew_anish', 'pew_samperr_anish']].copy()
final

                    pew_ella  pew_samperr_ella   pew_emily  pew_samperr_emily  \
obj_id feat_name
2004ef pW1         13.486097          8.617782         NaN                NaN
       pW2         12.432846          3.538539   11.949161           3.397220
       pW3         86.949994          6.117037   86.759862           8.132574
       pW4        174.768556          7.198777  174.768556           7.198777
       pW5         77.613915          4.167822   84.288745           5.536000
...                      ...               ...         ...                ...
2009ag pW4        145.155597          3.440187  146.469528           2.545504
       pW5         67.846124          1.994622   67.041939           2.695988
       pW6         15.765346          1.123412   15.827794           1.186468
       pW7        104.919371          0.494985  104.947436           0.498510
       pW8        272.556181          2.855016  272.556181           2.855016

                   pew_anish  pew_samperr_anish
obj_id feat_name
2004ef pW1         10.200355          19.901073
       pW2         12.432846           3.538539
       pW3         88.346404           6.506680
       pW4        174.768556           7.198777
       pW5         81.630045           2.541775
...                      ...                ...
2009ag pW4        140.409265           6.526490
       pW5         67.041939           2.695988
       pW6         14.622018           0.820812
       pW7        104.823633           0.571549
       pW8        272.556181           2.855016

[341 rows x 6 columns]